[package]

name = "libusb"
version = "0.0.1"
authors = ["David Cuddeback <david.cuddeback@gmail.com>"]
description = "Rust library for accessing USB devices."
license = "MIT"
homepage = "https://github.com/dcuddeback/libusb-rs"
repository = "https://github.com/dcuddeback/libusb-rs.git"

[dependencies]
libusb-sys = "0.0.1"

[dev-dependencies]
regex = "0.1.18"
